"""
Real-Time Monitoring System — Live Threat Monitoring with Webhooks & Alerts.

Fable 5 has no monitoring capability — it's a chat model.
Sentinel's Monitoring System provides:
1. Real-time analysis dashboard with live metrics
2. Webhook-based alerting (Slack, Discord, Email, PagerDuty)
3. Historical trend analysis with graphing data
4. Active threat tracking with status management
5. Performance metrics for all agents
6. Rate limiting and anomaly detection on scan patterns
"""

import asyncio
import json
import logging
import os
import time
import hashlib
import hmac
from typing import Dict, List, Optional, Any, Set, Callable
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from collections import defaultdict, deque

logger = logging.getLogger(__name__)


class AlertSeverity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


class AlertChannel(str, Enum):
    SLACK = "slack"
    DISCORD = "discord"
    EMAIL = "email"
    WEBHOOK = "webhook"
    PAGERDUTY = "pagerduty"
    CONSOLE = "console"


@dataclass
class Alert:
    """A security alert generated by the monitoring system."""
    id: str
    title: str
    message: str
    severity: AlertSeverity
    source: str
    channel: AlertChannel
    metadata: Dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    acknowledged: bool = False
    resolved: bool = False
    acknowledged_at: Optional[str] = None
    resolved_at: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "title": self.title,
            "message": self.message[:200],
            "severity": self.severity.value,
            "source": self.source,
            "channel": self.channel.value,
            "created_at": self.created_at,
            "acknowledged": self.acknowledged,
            "resolved": self.resolved,
        }


@dataclass
class MetricPoint:
    """A single metric data point for time-series analysis."""
    timestamp: float
    name: str
    value: float
    labels: Dict[str, str] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "timestamp": self.timestamp,
            "name": self.name,
            "value": self.value,
            "labels": self.labels,
        }


@dataclass
class ActiveThreat:
    """An actively tracked security threat."""
    id: str
    description: str
    severity: AlertSeverity
    source_agent: str
    affected_files: List[str]
    status: str  # "detected", "analyzing", "mitigating", "resolved"
    confidence: float
    created_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    updated_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    resolved_at: Optional[str] = None
    notes: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "description": self.description[:200],
            "severity": self.severity.value,
            "source": self.source_agent,
            "files": self.affected_files[:5],
            "status": self.status,
            "confidence": self.confidence,
            "created": self.created_at,
        }


class MonitoringSystem:
    """Real-time monitoring and alerting system for Sentinel.

    Provides:
    - Live metric collection from all agents
    - Multi-channel alerting (Slack, webhooks, console)
    - Active threat tracking with lifecycle management
    - Historical data for trend analysis
    - Rate limiting and scan pattern detection
    """

    def __init__(self):
        self._alerts: List[Alert] = []
        self._metrics: deque = deque(maxlen=10000)  # Keep last 10K data points
        self._active_threats: Dict[str, ActiveThreat] = {}
        self._resolved_threats: List[ActiveThreat] = []
        self._webhook_handlers: Dict[str, Callable] = {}
        self._rate_limits: Dict[str, deque] = defaultdict(lambda: deque(maxlen=100))

        # Webhook configuration
        self._webhook_urls: Dict[AlertChannel, str] = {}
        self._start_time = time.time()

        logger.info("Monitoring System initialized")

    def register_webhook(self, channel: AlertChannel, url: str):
        """Register a webhook URL for a notification channel."""
        self._webhook_urls[channel] = url
        logger.info(f"Registered webhook for {channel.value}: {url}")

    def register_handler(self, name: str, handler: Callable):
        """Register a custom alert handler function."""
        self._webhook_handlers[name] = handler
        logger.info(f"Registered alert handler: {name}")

    # ── Alert Management ──

    async def send_alert(
        self,
        title: str,
        message: str,
        severity: AlertSeverity = AlertSeverity.INFO,
        source: str = "sentinel",
        channel: AlertChannel = AlertChannel.CONSOLE,
        metadata: Optional[Dict] = None,
    ) -> Alert:
        """Send an alert through the specified channel.

        Args:
            title: Short alert title
            message: Detailed alert message
            severity: Alert severity level
            source: Source component
            channel: Delivery channel
            metadata: Additional data

        Returns:
            The created Alert object
        """
        alert = Alert(
            id=f"alert-{len(self._alerts) + 1}-{int(time.time())}",
            title=title,
            message=message,
            severity=severity,
            source=source,
            channel=channel,
            metadata=metadata or {},
        )

        self._alerts.append(alert)

        # Deliver alert
        await self._deliver_alert(alert)

        if severity in (AlertSeverity.CRITICAL, AlertSeverity.ERROR):
            logger.warning(f"Alert [{severity.value}]: {title}")
        else:
            logger.info(f"Alert [{severity.value}]: {title}")

        return alert

    async def _deliver_alert(self, alert: Alert):
        """Deliver an alert through its configured channel."""
        channel = alert.channel

        # Console delivery (always)
        console_msg = f"[{alert.severity.value.upper()}] {alert.title}: {alert.message[:200]}"
        print(console_msg)

        # Webhook delivery
        if channel == AlertChannel.SLACK:
            await self._deliver_slack(alert)
        elif channel == AlertChannel.DISCORD:
            await self._deliver_discord(alert)
        elif channel == AlertChannel.WEBHOOK:
            await self._deliver_webhook(alert)
        elif channel == AlertChannel.PAGERDUTY:
            await self._deliver_pagerduty(alert)

        # Custom handlers
        for name, handler in self._webhook_handlers.items():
            try:
                if asyncio.iscoroutinefunction(handler):
                    await handler(alert)
                else:
                    handler(alert)
            except Exception as e:
                logger.error(f"Handler '{name}' failed: {e}")

    async def _deliver_slack(self, alert: Alert):
        """Deliver alert to Slack webhook."""
        url = self._webhook_urls.get(AlertChannel.SLACK)
        if not url:
            return

        color_map = {
            AlertSeverity.CRITICAL: "#FF0000",
            AlertSeverity.ERROR: "#FF4500",
            AlertSeverity.WARNING: "#FFA500",
            AlertSeverity.INFO: "#1E90FF",
        }

        payload = {
            "attachments": [{
                "color": color_map.get(alert.severity, "#808080"),
                "title": f"[{alert.severity.value.upper()}] {alert.title}",
                "text": alert.message[:500],
                "fields": [
                    {"title": "Source", "value": alert.source, "short": True},
                    {"title": "Time", "value": alert.created_at, "short": True},
                ],
                "footer": "Sentinel Cyber AI Monitoring",
                "ts": int(time.time()),
            }]
        }

        try:
            import aiohttp
            async with aiohttp.ClientSession() as session:
                async with session.post(url, json=payload, timeout=10) as resp:
                    if resp.status != 200:
                        logger.warning(f"Slack delivery failed: {resp.status}")
        except ImportError:
            logger.warning("aiohttp not installed. Install with: pip install aiohttp")
        except Exception as e:
            logger.error(f"Slack delivery error: {e}")

    async def _deliver_discord(self, alert: Alert):
        """Deliver alert to Discord webhook."""
        url = self._webhook_urls.get(AlertChannel.DISCORD)
        if not url:
            return

        embed_color = {
            AlertSeverity.CRITICAL: 0xFF0000,
            AlertSeverity.ERROR: 0xFF4500,
            AlertSeverity.WARNING: 0xFFA500,
            AlertSeverity.INFO: 0x1E90FF,
        }

        payload = {
            "embeds": [{
                "title": f"[{alert.severity.value.upper()}] {alert.title}",
                "description": alert.message[:500],
                "color": embed_color.get(alert.severity, 0x808080),
                "fields": [
                    {"name": "Source", "value": alert.source, "inline": True},
                    {"name": "Time", "value": alert.created_at, "inline": True},
                ],
                "footer": {"text": "Sentinel Cyber AI"},
            }]
        }

        try:
            import aiohttp
            async with aiohttp.ClientSession() as session:
                async with session.post(url, json=payload, timeout=10) as resp:
                    if resp.status != 204:
                        logger.warning(f"Discord delivery failed: {resp.status}")
        except ImportError:
            pass
        except Exception as e:
            logger.error(f"Discord delivery error: {e}")

    async def _deliver_webhook(self, alert: Alert):
        """Deliver alert to generic webhook."""
        url = self._webhook_urls.get(AlertChannel.WEBHOOK)
        if not url:
            return

        payload = {
            "event": "sentinel_alert",
            "alert": alert.to_dict(),
            "timestamp": datetime.utcnow().isoformat(),
        }

        try:
            import aiohttp
            async with aiohttp.ClientSession() as session:
                async with session.post(url, json=payload, timeout=10) as resp:
                    if resp.status not in (200, 201, 202, 204):
                        logger.warning(f"Webhook delivery failed: {resp.status}")
        except ImportError:
            pass
        except Exception as e:
            logger.error(f"Webhook delivery error: {e}")

    async def _deliver_pagerduty(self, alert: Alert):
        """Deliver alert to PagerDuty."""
        url = self._webhook_urls.get(AlertChannel.PAGERDUTY)
        if not url:
            return

        severity_map = {
            AlertSeverity.CRITICAL: "critical",
            AlertSeverity.ERROR: "error",
            AlertSeverity.WARNING: "warning",
            AlertSeverity.INFO: "info",
        }

        payload = {
            "routing_key": url,
            "event_action": "trigger",
            "payload": {
                "summary": alert.title[:120],
                "severity": severity_map.get(alert.severity, "info"),
                "source": alert.source,
                "custom_details": alert.metadata,
                "timestamp": alert.created_at,
            },
        }

        try:
            import aiohttp
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    "https://events.pagerduty.com/v2/enqueue",
                    json=payload,
                    timeout=10,
                ) as resp:
                    if resp.status not in (200, 202):
                        logger.warning(f"PagerDuty delivery failed: {resp.status}")
        except ImportError:
            pass
        except Exception as e:
            logger.error(f"PagerDuty delivery error: {e}")

    def acknowledge_alert(self, alert_id: str) -> bool:
        """Acknowledge an alert."""
        for alert in self._alerts:
            if alert.id == alert_id:
                alert.acknowledged = True
                alert.acknowledged_at = datetime.utcnow().isoformat()
                return True
        return False

    def resolve_alert(self, alert_id: str) -> bool:
        """Resolve an alert."""
        for alert in self._alerts:
            if alert.id == alert_id:
                alert.resolved = True
                alert.resolved_at = datetime.utcnow().isoformat()
                return True
        return False

    # ── Metric Collection ──

    def record_metric(self, name: str, value: float, labels: Optional[Dict[str, str]] = None):
        """Record a metric data point."""
        point = MetricPoint(
            timestamp=time.time(),
            name=name,
            value=value,
            labels=labels or {},
        )
        self._metrics.append(point)

    def get_metrics(self, name: Optional[str] = None,
                    since: Optional[float] = None,
                    limit: int = 100) -> List[MetricPoint]:
        """Get metric data points with optional filtering.

        Args:
            name: Filter by metric name
            since: Only return points after this timestamp
            limit: Maximum number of points to return
        """
        results = []
        for point in self._metrics:
            if name and point.name != name:
                continue
            if since and point.timestamp < since:
                continue
            results.append(point)
            if len(results) >= limit:
                break
        return results

    def get_metric_summary(self, name: str, duration_seconds: int = 3600) -> Dict[str, float]:
        """Get summary statistics for a metric over a time period."""
        since = time.time() - duration_seconds
        points = self.get_metrics(name=name, since=since)

        if not points:
            return {"count": 0, "avg": 0, "min": 0, "max": 0, "sum": 0}

        values = [p.value for p in points]
        return {
            "count": len(values),
            "avg": sum(values) / len(values),
            "min": min(values),
            "max": max(values),
            "sum": sum(values),
            "latest": values[-1],
        }

    # ── Active Threat Tracking ──

    def track_threat(self, description: str, severity: AlertSeverity,
                     source_agent: str, affected_files: List[str],
                     confidence: float = 0.8) -> ActiveThreat:
        """Register a new active threat for tracking.

        Args:
            description: Threat description
            severity: Threat severity
            source_agent: Which agent detected it
            affected_files: Files involved
            confidence: Detection confidence

        Returns:
            The created ActiveThreat
        """
        threat = ActiveThreat(
            id=f"threat-{len(self._active_threats) + len(self._resolved_threats) + 1}-{int(time.time())}",
            description=description,
            severity=severity,
            source_agent=source_agent,
            affected_files=affected_files,
            status="detected",
            confidence=confidence,
        )
        self._active_threats[threat.id] = threat
        logger.info(f"New threat tracked: {threat.id} ({severity.value})")
        return threat

    def update_threat_status(self, threat_id: str, status: str, note: Optional[str] = None) -> bool:
        """Update the status of an active threat."""
        threat = self._active_threats.get(threat_id)
        if not threat:
            return False

        threat.status = status
        threat.updated_at = datetime.utcnow().isoformat()

        if note:
            threat.notes.append(f"[{datetime.utcnow().isoformat()}] {note}")

        if status == "resolved":
            threat.resolved_at = datetime.utcnow().isoformat()
            self._resolved_threats.append(threat)
            del self._active_threats[threat_id]

        logger.info(f"Threat {threat_id} status -> {status}")
        return True

    def get_active_threats(self, severity: Optional[AlertSeverity] = None) -> List[ActiveThreat]:
        """Get all active threats, optionally filtered by severity."""
        threats = list(self._active_threats.values())
        if severity:
            threats = [t for t in threats if t.severity == severity]
        return sorted(threats, key=lambda t: t.created_at, reverse=True)

    # ── Rate Limiting ──

    def check_rate_limit(self, key: str, max_requests: int = 60,
                         window_seconds: int = 60) -> bool:
        """Check if a key has exceeded its rate limit.

        Args:
            key: The rate limit key (e.g., IP, API key)
            max_requests: Maximum requests allowed in the window
            window_seconds: Time window in seconds

        Returns:
            True if within limit, False if exceeded
        """
        now = time.time()
        window = self._rate_limits[key]

        # Clean old entries
        while window and window[0] < now - window_seconds:
            window.popleft()

        if len(window) >= max_requests:
            logger.warning(f"Rate limit exceeded for {key}")
            return False

        window.append(now)
        return True

    # ── Dashboard Data ──

    def get_dashboard_data(self) -> Dict[str, Any]:
        """Get all data needed for a real-time dashboard."""
        # Recent alerts
        recent_alerts = [
            a.to_dict() for a in self._alerts[-20:]
        ]

        # Active threats
        active = [
            t.to_dict() for t in self._active_threats.values()
        ]

        # Metric summaries
        metrics_summary = {
            "analyses_per_minute": self.get_metric_summary("analysis_rate", 60),
            "avg_confidence": self.get_metric_summary("confidence", 3600),
            "detection_rate": self.get_metric_summary("detections", 3600),
            "error_rate": self.get_metric_summary("errors", 3600),
            "avg_latency_ms": self.get_metric_summary("latency_ms", 3600),
            "throughput": self.get_metric_summary("throughput", 60),
        }

        # Alert statistics
        alert_stats = {
            "total": len(self._alerts),
            "critical": sum(1 for a in self._alerts if a.severity == AlertSeverity.CRITICAL),
            "error": sum(1 for a in self._alerts if a.severity == AlertSeverity.ERROR),
            "warning": sum(1 for a in self._alerts if a.severity == AlertSeverity.WARNING),
            "info": sum(1 for a in self._alerts if a.severity == AlertSeverity.INFO),
            "acknowledged": sum(1 for a in self._alerts if a.acknowledged),
            "resolved": sum(1 for a in self._alerts if a.resolved),
        }

        return {
            "timestamp": datetime.utcnow().isoformat(),
            "uptime_seconds": time.time() - self._start_time if hasattr(self, '_start_time') else 0,
            "alerts": {
                "recent": recent_alerts,
                "stats": alert_stats,
            },
            "active_threats": {
                "count": len(active),
                "list": active,
            },
            "metrics": metrics_summary,
            "rate_limits": {
                key: len(queue) for key, queue in self._rate_limits.items()
            },
        }

    def get_status(self) -> Dict[str, Any]:
        """Get monitoring system status."""
        return {
            "total_alerts": len(self._alerts),
            "active_threats": len(self._active_threats),
            "resolved_threats": len(self._resolved_threats),
            "metrics_collected": len(self._metrics),
            "webhooks_configured": len(self._webhook_urls),
            "webhook_channels": [c.value for c in self._webhook_urls],
            "custom_handlers": len(self._webhook_handlers),
            "active_rate_limits": len(self._rate_limits),
            "metric_names": list(set(m.name for m in self._metrics)),
        }
