#!/usr/bin/env bash
set -euo pipefail

exec > >(tee /var/log/sentinel-bootstrap.log | logger -t sentinel-bootstrap) 2>&1

echo "=== Sentinel Bootstrap ==="
date

# Update & install deps
apt-get update -qq && apt-get upgrade -y -qq
apt-get install -y -qq curl git openssl python3 python3-pip ufw unzip jq ca-certificates gnupg lsb-release

# Install Docker
curl -fsSL https://get.docker.com | sh
usermod -aG docker ubuntu
systemctl enable docker
systemctl start docker

# Clone repo
rm -rf /opt/sentinel
git clone --branch "${git_branch}" --depth 1 "${git_repo_url}" /opt/sentinel 2>&1 || echo "Git clone failed - deploy code manually or check repo URL: ${git_repo_url}"
cd /opt/sentinel

# Create .env
echo "# Generated by Terraform" > /opt/sentinel/.env
echo "SENTINEL_API_KEY=${api_key}" >> /opt/sentinel/.env
echo "SENTINEL_CORS_ORIGINS=${cors_origins}" >> /opt/sentinel/.env
echo "SENTINEL_LOG_LEVEL=INFO" >> /opt/sentinel/.env
echo "TZ=UTC" >> /opt/sentinel/.env

if [ "${enable_rds}" = "true" ] && [ -n "${rds_endpoint}" ]; then
  echo "DATABASE_URL=postgresql+asyncpg://${rds_user}:${rds_password}@${rds_endpoint}/${rds_db_name}" >> /opt/sentinel/.env
fi

if [ -n "${github_token}" ]; then echo "GITHUB_TOKEN=${github_token}" >> /opt/sentinel/.env; fi
if [ -n "${slack_webhook}" ]; then echo "SLACK_WEBHOOK_URL=${slack_webhook}" >> /opt/sentinel/.env; fi
if [ -n "${discord_webhook}" ]; then echo "DISCORD_WEBHOOK_URL=${discord_webhook}" >> /opt/sentinel/.env; fi
if [ -n "${s3_backups_bucket}" ]; then echo "BACKUP_S3_BUCKET=${s3_backups_bucket}" >> /opt/sentinel/.env; fi

# Create dirs
mkdir -p /opt/sentinel/data/processed /opt/sentinel/outputs/models /opt/sentinel/outputs/reports /opt/sentinel/docker/nginx/ssl

# SSL fallback
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /opt/sentinel/docker/nginx/ssl/key.pem -out /opt/sentinel/docker/nginx/ssl/cert.pem -subj "/CN=sentinel.local" 2>/dev/null

# Start services
cd /opt/sentinel
docker compose -f docker/docker-compose.prod.yml build
docker compose -f docker/docker-compose.prod.yml up -d

# Health check
sleep 15
for i in $(seq 1 12); do
  if curl -sf http://localhost:8080/health > /dev/null 2>&1; then
    echo "API is healthy!"; break
  fi
  echo "Waiting for API... (attempt $i/12)"
  sleep 10
done

# Firewall
ufw --force reset && ufw default deny incoming && ufw default allow outgoing
ufw allow ssh && ufw allow http && ufw allow https && ufw --force enable

echo "=== Complete ==="
date
