"""
Self-Play Learning Pipeline — Autonomous Security Improvement System.

This is what makes Sentinel fundamentally more powerful than Fable 5:
Fable 5 is a static model. Sentinel learns and improves over time.

v2.0 Enhancement: Real Model-in-the-Loop
- Uses actual LLM inference (via InferenceEngine) to generate realistic vuln/secure code
- Template generation + model-based generation for richer training data
- Automatic dataset creation for fine-tuning pipeline
- Confidence-weighted training example selection
"""

import asyncio
import json
import logging
import os
import random
import time
import hashlib
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from collections import defaultdict

logger = logging.getLogger(__name__)

# Try to import the real inference engine
try:
    from src.models.llm_backend import InferenceEngine, ModelRegistry
    HAS_INFERENCE_ENGINE = True
except ImportError:
    HAS_INFERENCE_ENGINE = False
    InferenceEngine = None
    ModelRegistry = None


class LearningPhase(str, Enum):
    DATA_GENERATION = "data_generation"
    PATTERN_DISCOVERY = "pattern_discovery"
    MODEL_TRAINING = "model_training"
    BENCHMARK_EVAL = "benchmark_evaluation"
    KNOWLEDGE_DISTILLATION = "knowledge_distillation"
    DEPLOYMENT = "deployment"


class ImprovementType(str, Enum):
    NEW_PATTERN = "new_pattern"
    CONFIDENCE_TUNE = "confidence_tune"
    FALSE_POSITIVE_REDUCTION = "false_positive_reduction"
    COVERAGE_EXPANSION = "coverage_expansion"
    PERFORMANCE_OPTIMIZATION = "performance_optimization"
    EXPLOIT_CHAIN_IMPROVEMENT = "exploit_chain_improvement"


@dataclass
class TrainingExample:
    """A single training example generated from real analysis."""
    id: str
    query: str
    code_context: str
    expected_findings: List[Dict[str, Any]]
    actual_findings: List[Dict[str, Any]]
    confidence_score: float
    source_agent: str
    vulnerability_type: str
    difficulty: str  # easy, medium, hard, expert
    is_positive: bool  # True = has vuln, False = clean code
    created_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    used_in_training: bool = False
    improvement_impact: Optional[float] = None
    model_generated: bool = False  # NEW: True if generated by real LLM

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "query": self.query[:200],
            "expected_findings": len(self.expected_findings),
            "actual_findings": len(self.actual_findings),
            "confidence": self.confidence_score,
            "source": self.source_agent,
            "vuln_type": self.vulnerability_type,
            "difficulty": self.difficulty,
            "is_positive": self.is_positive,
            "used": self.used_in_training,
            "impact": self.improvement_impact,
            "model_generated": self.model_generated,
        }

    def to_training_format(self) -> Dict[str, str]:
        """Convert to chat training format for fine-tuning pipeline.
        
        Produces instruction/input/output tuples consumable by train_sentinel.py.
        """
        vuln_types = ", ".join(
            f.get("type", "unknown") for f in self.expected_findings
        )
        severity = max(
            (f.get("severity", "LOW") for f in self.expected_findings),
            key=lambda s: {"CRITICAL": 4, "HIGH": 3, "MEDIUM": 2, "LOW": 1}.get(s, 0),
        ) if self.expected_findings else "INFO"

        if self.is_positive:
            instruction = f"Find and fix the {vuln_types} vulnerability in this code."
            output = f"## Vulnerability: {vuln_types.title()}\n\n**Severity: {severity}**\n\nThe code contains a {vuln_types} vulnerability. "
            output += f"Confidence: {self.confidence_score:.0%}.\n\n"
            if self.expected_findings:
                for f in self.expected_findings:
                    if f.get("description"):
                        output += f"{f['description']}\n"
                    if f.get("remediation"):
                        output += f"\n### Fix:\n{f['remediation']}\n"
        else:
            instruction = "Review this code for security vulnerabilities."
            output = "## Security Review\n\n**Severity: INFO**\n\nNo security vulnerabilities detected in this code. The implementation follows security best practices."

        return {
            "instruction": instruction,
            "input": f"```\n{self.code_context}\n```",
            "output": output,
        }


@dataclass
class DiscoveredPattern:
    """A novel vulnerability pattern discovered through self-play."""
    id: str
    name: str
    description: str
    detection_pattern: str  # regex or code pattern
    severity: str
    cwe_mapping: Optional[str]
    discovery_source: str  # which analysis led to this
    confidence: float
    times_matched: int = 0
    false_positive_count: int = 0
    created_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())

    @property
    def accuracy(self) -> float:
        total = self.times_matched + self.false_positive_count
        return self.times_matched / total if total > 0 else 0.0


@dataclass
class SelfPlayStats:
    """Self-play system statistics."""
    total_training_examples: int = 0
    total_patterns_discovered: int = 0
    total_improvement_cycles: int = 0
    average_confidence_improvement: float = 0.0
    false_positive_reduction: float = 0.0
    coverage_expansion: float = 0.0
    last_training_time: Optional[str] = None
    active_patterns: int = 0
    total_vulnerability_types_covered: int = 0
    model_generated_examples: int = 0  # NEW


# ── Vulnerability templates for generating training data ──

VULNERABILITY_TEMPLATES = [
    {
        "type": "sql_injection",
        "cwe": "CWE-89",
        "severity": "CRITICAL",
        "code_patterns": [
            "f\"SELECT * FROM users WHERE username = '{username}'\"",
            "\"SELECT * FROM users WHERE id = \" + user_id",
            "cursor.execute(f\"SELECT * FROM {table} WHERE id = {id}\")",
            "query = 'SELECT * FROM items WHERE name LIKE \"%' + search + '%\"'",
        ],
        "secure_patterns": [
            "cursor.execute(\"SELECT * FROM users WHERE username = ?\", (username,))",
            "query = \"SELECT * FROM users WHERE id = :id\"",
            "cursor.execute(\"SELECT * FROM items WHERE name LIKE ?\", ('%' + search + '%',))",
        ],
    },
    {
        "type": "xss",
        "cwe": "CWE-79",
        "severity": "HIGH",
        "code_patterns": [
            "document.getElementById('output').innerHTML = userInput",
            "response.write(f\"<div>{user_content}</div>\")",
            "$('#result').html(user_data)",
            "Element.innerHTML = untrusted_input",
        ],
        "secure_patterns": [
            "document.getElementById('output').textContent = userInput",
            "response.write(escape_html(user_content))",
            "$('#result').text(user_data)",
            "Element.textContent = sanitized_input",
        ],
    },
    {
        "type": "command_injection",
        "cwe": "CWE-78",
        "severity": "CRITICAL",
        "code_patterns": [
            "os.system(f\"ping {host}\")",
            "subprocess.run(cmd, shell=True)",
            "exec(f\"nslookup {domain}\")",
            "os.popen(f\"traceroute {ip_address}\")",
        ],
        "secure_patterns": [
            "subprocess.run([\"ping\", host], capture_output=True)",
            "subprocess.run(cmd.split(), shell=False)",
            "import shlex; subprocess.run(shlex.split(cmd))",
        ],
    },
    {
        "type": "path_traversal",
        "cwe": "CWE-22",
        "severity": "HIGH",
        "code_patterns": [
            "open(f\"/var/data/{filename}\", 'r').read()",
            "File.ReadAllText($\"files/{userInput}\")",
            "with open(os.path.join(base_path, filename)) as f:",
            "Path.join('uploads', user_provided_name)",
        ],
        "secure_patterns": [
            "safe = os.path.normpath(os.path.join(base, filename))",
            "if not safe_path.startswith(base_path): raise ValueError()",
            "filename = os.path.basename(user_filename)",
        ],
    },
    {
        "type": "insecure_deserialization",
        "cwe": "CWE-502",
        "severity": "CRITICAL",
        "code_patterns": [
            "pickle.loads(untrusted_data)",
            "yaml.load(user_input)",
            "eval(base64.b64decode(encoded_data))",
            "jsonpickle.decode(request.body)",
        ],
        "secure_patterns": [
            "json.loads(untrusted_data)",
            "yaml.safe_load(user_input)",
            "import msgpack; msgpack.unpackb(data, raw=False)",
        ],
    },
    {
        "type": "xxe_injection",
        "cwe": "CWE-611",
        "severity": "HIGH",
        "code_patterns": [
            "from lxml import etree; etree.parse(xml_input)",
            "xml.etree.ElementTree.fromstring(user_xml)",
            "DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(inputStream)",
            "SimpleXMLElement($userInput)",
        ],
        "secure_patterns": [
            "parser = etree.XMLParser(resolve_entities=False)",
            "from defusedxml import ElementTree; ElementTree.fromstring(user_xml)",
            "DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance(); factory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true)",
        ],
    },
    {
        "type": "ssrf",
        "cwe": "CWE-918",
        "severity": "HIGH",
        "code_patterns": [
            "requests.get(user_provided_url)",
            "urlopen(request.GET['url'])",
            "HttpClient.GetAsync(inputUrl)",
            "fetch(userSuppliedEndpoint)",
        ],
        "secure_patterns": [
            "ALLOWED_HOSTS = ['api.internal.com', 'data.trusted.com']",
            "parsed = urlparse(user_url); assert parsed.hostname in ALLOWED_HOSTS",
            "if not is_safe_url(url): raise ValueError()",
        ],
    },
    {
        "type": "idors",
        "cwe": "CWE-639",
        "severity": "HIGH",
        "code_patterns": [
            "db.query(f\"SELECT * FROM documents WHERE id = {doc_id}\")",
            "Document.find(params[:id])",
            "db.documents.find({_id: ObjectId(req.params.id)})",
        ],
        "secure_patterns": [
            "db.query(\"SELECT * FROM documents WHERE id = ? AND user_id = ?\", (doc_id, user_id))",
            "Document.where(id: params[:id], user_id: current_user.id).first",
            "db.documents.findOne({_id: req.params.id, user_id: req.user.id})",
        ],
    },
    {
        "type": "hardcoded_credentials",
        "cwe": "CWE-798",
        "severity": "MEDIUM",
        "code_patterns": [
            "PASSWORD = 'supersecret123!'",
            "API_KEY = 'sk-abc123def456ghi789'",
            "db_password = \"admin123\"",
            "secret_key = 'secret!@#$%'",
        ],
        "secure_patterns": [
            "PASSWORD = os.environ.get('DB_PASSWORD')",
            "API_KEY = os.environ['OPENAI_API_KEY']",
            "from dotenv import load_dotenv; load_dotenv()",
        ],
    },
    {
        "type": "security_misconfiguration",
        "cwe": "CWE-200",
        "severity": "MEDIUM",
        "code_patterns": [
            "app.debug = True",
            "CORS(app, resources={r\"/*\": {\"origins\": \"*\"}})",
            "ALLOWED_HOSTS = ['*']",
            "DEBUG = True",
        ],
        "secure_patterns": [
            "app.debug = False",
            "CORS(app, resources={r\"/api/*\": {\"origins\": [\"https://app.com\"]}})",
            "ALLOWED_HOSTS = ['app.com', 'api.app.com']",
        ],
    },
]


class SelfPlayLearningPipeline:
    """Autonomous self-improvement system for Sentinel.

    Fable 5 is a static model - it never improves without Anthropic retraining it.
    Sentinel's Self-Play Pipeline continuously learns and improves:

    1. GENERATE: Run analyses on known vulnerable/clean code
    2. COMPARE: Compare results against expected findings
    3. DISCOVER: Find patterns in false positives/negatives
    4. IMPROVE: Update detection rules and confidence thresholds
    5. VALIDATE: Run benchmarks to measure improvement
    6. DEPLOY: Push improvements to the active system

    v2.0: Now uses real LLM inference for model-in-the-loop generation,
    producing richer, more realistic training data than static templates.
    """

    def __init__(self, orchestrator=None, storage_dir: Optional[str] = None):
        self._orchestrator = orchestrator
        self.storage_dir = storage_dir or os.path.expanduser("~/.cache/sentinel/learning")
        os.makedirs(self.storage_dir, exist_ok=True)

        self.examples: List[TrainingExample] = []
        self.discovered_patterns: List[DiscoveredPattern] = []
        self.improvement_history: List[Dict[str, Any]] = []
        self.stats = SelfPlayStats()

        # Initialize inference engine for model-in-the-loop generation
        self._inference_engine = None
        if HAS_INFERENCE_ENGINE:
            try:
                registry = ModelRegistry()
                self._inference_engine = InferenceEngine(registry)
                logger.info("Self-play: Inference engine ready for model-in-the-loop generation")
            except Exception as e:
                logger.warning(f"Self-play: Could not initialize inference engine: {e}")

        self._load_state()
        logger.info(f"Self-Play Pipeline initialized ({len(self.examples)} examples, "
                     f"{len(self.discovered_patterns)} patterns)")

    def _load_state(self):
        """Load saved state from disk."""
        examples_path = os.path.join(self.storage_dir, "training_examples.json")
        patterns_path = os.path.join(self.storage_dir, "discovered_patterns.json")
        stats_path = os.path.join(self.storage_dir, "selfplay_stats.json")

        for path, attr, cls in [
            (examples_path, "examples", TrainingExample),
            (patterns_path, "discovered_patterns", DiscoveredPattern),
            (stats_path, "stats", None),
        ]:
            if os.path.exists(path):
                try:
                    with open(path, "r") as f:
                        data = json.load(f)
                    if cls:
                        setattr(self, attr, [cls(**item) for item in data])
                    else:
                        self.stats = SelfPlayStats(**data)
                except Exception as e:
                    logger.warning(f"Could not load {path}: {e}")

    def _save_state(self):
        """Save state to disk."""
        examples_path = os.path.join(self.storage_dir, "training_examples.json")
        patterns_path = os.path.join(self.storage_dir, "discovered_patterns.json")
        stats_path = os.path.join(self.storage_dir, "selfplay_stats.json")

        try:
            with open(examples_path, "w") as f:
                json.dump([e.to_dict() for e in self.examples[-1000:]], f, indent=2)
            with open(patterns_path, "w") as f:
                json.dump([p.__dict__ for p in self.discovered_patterns], f, indent=2)
            with open(stats_path, "w") as f:
                json.dump(self.stats.__dict__, f, indent=2)
        except Exception as e:
            logger.warning(f"Could not save state: {e}")

    def set_orchestrator(self, orchestrator):
        self._orchestrator = orchestrator

    # ── Data Generation (v2.0: Model-in-the-Loop) ──

    async def generate_training_batch(
        self,
        count: int = 50,
        use_model_generation: bool = False,
        model_generation_ratio: float = 0.4,
    ) -> List[TrainingExample]:
        """Generate training examples using BOTH templates AND real LLM inference.

        v2.0 Enhancement:
        - Uses the real LLM backend (InferenceEngine) to generate realistic code
        - Templates provide guaranteed coverage; model generation adds richness
        - model_generation_ratio controls the mix (default 40% when enabled)
        - Default is False for backward compatibility — opt-in via use_model_generation=True

        Args:
            count: Total number of examples to generate
            use_model_generation: Whether to use model-in-the-loop generation
            model_generation_ratio: Fraction of examples generated by real LLM

        Returns:
            List of TrainingExample objects
        """
        examples = []
        model_count = int(count * model_generation_ratio) if use_model_generation else 0
        template_count = count - model_count

        # Generate model-based examples (richer, more realistic)
        if model_count > 0 and self._inference_engine is not None:
            try:
                model_examples = await self._generate_model_based(model_count)
                examples.extend(model_examples)
                logger.info(f"Generated {len(model_examples)} model-based training examples")
            except Exception as e:
                logger.warning(f"Model-based generation failed, falling back to templates: {e}")
                template_count = count

        # Generate template-based examples (guaranteed coverage)
        for i in range(template_count):
            template = random.choice(VULNERABILITY_TEMPLATES)
            is_positive = random.choice([True, False])

            if is_positive:
                code = random.choice(template["code_patterns"])
            else:
                code = random.choice(template["secure_patterns"])

            query = f"Analyze this code for vulnerabilities:\n```\n{code}\n```"

            example_id = hashlib.md5(
                f"{query}{time.time()}{i}".encode()
            ).hexdigest()[:12]

            example = TrainingExample(
                id=example_id,
                query=query,
                code_context=code,
                expected_findings=[{
                    "type": template["type"],
                    "cwe": template["cwe"],
                    "severity": template["severity"],
                    "present": is_positive,
                }],
                actual_findings=[],
                confidence_score=0.0,
                source_agent="self-play-generator",
                vulnerability_type=template["type"],
                difficulty="medium" if is_positive else "easy",
                is_positive=is_positive,
                model_generated=False,
            )
            examples.append(example)

        self.examples.extend(examples)
        self.stats.total_training_examples += len(examples)
        self.stats.model_generated_examples += model_count
        self._save_state()
        return examples

    async def _generate_model_based(self, count: int) -> List[TrainingExample]:
        """Generate training examples using real LLM inference.

        Uses the InferenceEngine to:
        1. Generate realistic vulnerable code with context (real function names, imports, etc.)
        2. Generate secure versions of the same functionality
        3. Produce natural-looking code that tests the agents more realistically

        This is the key v2.0 improvement — real model output > static templates.
        """
        examples = []
        engine = self._inference_engine

        # Generate mixed examples using the model
        for i in range(count):
            template = random.choice(VULNERABILITY_TEMPLATES)
            is_positive = random.choice([True, False])

            try:
                # Use the model to generate realistic code with this vulnerability type
                if is_positive:
                    prompt = (
                        f"Write a short Python function (3-10 lines) that contains a "
                        f"{template['type']} vulnerability (CWE-{template['cwe']}). "
                        f"Make it look like real production code with realistic variable names. "
                        f"Return ONLY the code, no explanation."
                    )
                else:
                    prompt = (
                        f"Write a short Python function (3-10 lines) that demonstrates "
                        f"secure coding practices and does NOT contain a {template['type']} vulnerability. "
                        f"Make it look like real production code with realistic variable names. "
                        f"Return ONLY the code, no explanation."
                    )

                response = await engine.analyze_security(
                    code=prompt,
                    task="patch_generation",
                    model_id="qwen3-8b",
                )

                # Extract code from response
                code = self._extract_code_from_response(response)
                if not code or len(code) < 20:
                    # Fall back to template if model output isn't usable
                    code = random.choice(
                        template["code_patterns"] if is_positive else template["secure_patterns"]
                    )

            except Exception as e:
                logger.warning(f"Model generation failed for {template['type']}: {e}")
                code = random.choice(
                    template["code_patterns"] if is_positive else template["secure_patterns"]
                )

            query = f"Analyze this code for vulnerabilities:\n```\n{code}\n```"
            example_id = hashlib.md5(f"{query}{time.time()}{i}".encode()).hexdigest()[:12]

            example = TrainingExample(
                id=example_id,
                query=query,
                code_context=code,
                expected_findings=[{
                    "type": template["type"],
                    "cwe": template["cwe"],
                    "severity": template["severity"],
                    "present": is_positive,
                }],
                actual_findings=[],
                confidence_score=0.0,
                source_agent="self-play-model",
                vulnerability_type=template["type"],
                difficulty="hard" if is_positive else "medium",
                is_positive=is_positive,
                model_generated=True,
            )
            examples.append(example)

        return examples

    def _extract_code_from_response(self, response: str) -> Optional[str]:
        """Extract code from model response."""
        if not response:
            return None

        # Try code blocks first
        import re
        code_blocks = re.findall(r"```(?:\w+)?\n(.*?)```", response, re.DOTALL)
        if code_blocks:
            return code_blocks[0].strip()

        # Use the raw response if it looks like code
        response = response.strip()
        if any(kw in response for kw in ["def ", "import ", "class ", "from "]):
            return response

        return None

    async def evaluate_example(
        self, example: TrainingExample
    ) -> TrainingExample:
        """Run an example through the orchestrator and compare results."""
        if not self._orchestrator:
            example.confidence_score = 0.5
            return example

        try:
            result = await self._orchestrator.process(example.query)
            actual_findings = result.get("findings", [])
            confidence = result.get("confidence", 0)

            example.actual_findings = actual_findings
            example.confidence_score = confidence

            # Score how well we did
            expected_vuln_type = example.expected_findings[0]["type"]
            expected_present = example.expected_findings[0]["present"]

            found_matching = any(
                expected_vuln_type in str(f.get("title", "")).lower()
                or expected_vuln_type in str(f.get("description", "")).lower()
                for f in actual_findings
            )

            if expected_present and found_matching:
                example.improvement_impact = 1.0  # Correct detection
            elif expected_present and not found_matching:
                example.improvement_impact = 0.0  # Missed it - FALSE NEGATIVE
            elif not expected_present and found_matching:
                example.improvement_impact = 0.0  # False alarm - FALSE POSITIVE
            else:
                example.improvement_impact = 1.0  # Correctly identified as clean

        except Exception as e:
            logger.error(f"Example evaluation failed: {e}")
            example.confidence_score = 0.0
            example.improvement_impact = 0.0

        return example

    # ── Dataset Export for Fine-Tuning ──

    def export_training_dataset(
        self,
        output_path: str,
        min_confidence: float = 0.0,
        max_examples: int = 1000,
        include_model_generated: bool = True,
    ) -> str:
        """Export training examples as a JSONL dataset for the fine-tuning pipeline.

        v2.0 Enhancement: Connects self-play → training pipeline.
        The output can be consumed by scripts/train_sentinel.py directly.

        Args:
            output_path: Path for the output JSONL file
            min_confidence: Minimum confidence threshold for inclusion
            max_examples: Maximum number of examples to export
            include_model_generated: Include model-generated examples

        Returns:
            Path to the exported dataset
        """
        # Filter examples
        candidates = [
            e for e in self.examples
            if e.confidence_score >= min_confidence
            and (include_model_generated or not e.model_generated)
            and e.improvement_impact is not None
            and e.improvement_impact >= 0.5  # Only include high-impact examples
        ]

        # Sort by improvement impact (best examples first)
        candidates.sort(key=lambda e: -(e.improvement_impact or 0))

        # Limit
        candidates = candidates[:max_examples]

        # Write JSONL
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            for example in candidates:
                training_format = example.to_training_format()
                f.write(json.dumps(training_format, ensure_ascii=False) + "\n")

        logger.info(
            f"Exported {len(candidates)} training examples to {output_path} "
            f"({sum(1 for e in candidates if e.model_generated)} model-generated)"
        )
        return output_path

    def export_train_val_split(
        self,
        output_dir: str,
        train_ratio: float = 0.9,
        min_confidence: float = 0.0,
        max_examples: int = 1000,
    ) -> Tuple[str, str]:
        """Export train/validation split for the fine-tuning pipeline.

        Args:
            output_dir: Directory to write the split files
            train_ratio: Proportion of examples for training
            min_confidence: Minimum confidence threshold
            max_examples: Maximum examples to export

        Returns:
            Tuple of (train_path, val_path)
        """
        os.makedirs(output_dir, exist_ok=True)

        # Get all high-quality examples
        candidates = [
            e for e in self.examples
            if e.confidence_score >= min_confidence
            and e.improvement_impact is not None
            and e.improvement_impact >= 0.5
        ]
        candidates.sort(key=lambda e: -(e.improvement_impact or 0))
        candidates = candidates[:max_examples]

        # Shuffle for split
        random.shuffle(candidates)
        split_idx = int(len(candidates) * train_ratio)

        train_examples = candidates[:split_idx]
        val_examples = candidates[split_idx:]

        # Write files
        train_path = os.path.join(output_dir, "selfplay_train.jsonl")
        val_path = os.path.join(output_dir, "selfplay_val.jsonl")

        for path, examples in [(train_path, train_examples), (val_path, val_examples)]:
            with open(path, "w", encoding="utf-8") as f:
                for ex in examples:
                    f.write(json.dumps(ex.to_training_format(), ensure_ascii=False) + "\n")

        logger.info(
            f"Exported train/val split: {len(train_examples)} train, {len(val_examples)} val\n"
            f"  Train: {train_path}\n  Val: {val_path}"
        )
        return train_path, val_path

    # ── Pattern Discovery ──

    def discover_patterns_from_failures(self, examples: List[TrainingExample]) -> List[DiscoveredPattern]:
        """Analyze false positives and false negatives to discover new patterns.

        This is the core learning mechanism — when Sentinel makes a mistake,
        it figures out WHY and creates a new pattern to catch it next time.

        Fable 5 has no equivalent — it can't learn from its mistakes
        without Anthropic retraining the entire model.
        """
        new_patterns = []

        # Analyze false negatives (missed vulnerabilities)
        false_negatives = [
            e for e in examples
            if e.is_positive and e.improvement_impact is not None and e.improvement_impact < 0.5
        ]

        if false_negatives:
            # Group by vulnerability type
            by_type: Dict[str, List[TrainingExample]] = {}
            for fn in false_negatives:
                by_type.setdefault(fn.vulnerability_type, []).append(fn)

            for vuln_type, fns in by_type.items():
                if len(fns) >= 3:  # Need enough data to discover a pattern
                    template = next(
                        (t for t in VULNERABILITY_TEMPLATES if t["type"] == vuln_type),
                        None,
                    )
                    if template:
                        pattern = DiscoveredPattern(
                            id=f"pattern-{len(self.discovered_patterns) + 1}",
                            name=f"Enhanced {vuln_type.replace('_', ' ').title()} Detection",
                            description=(
                                f"Auto-discovered detection enhancement for {vuln_type}. "
                                f"Sentinel missed {len(fns)} instances. "
                                f"Adding additional detection vectors."
                            ),
                            detection_pattern=template["code_patterns"][0],
                            severity=template["severity"],
                            cwe_mapping=template["cwe"],
                            discovery_source="false_negative_analysis",
                            confidence=0.7,
                        )
                        new_patterns.append(pattern)

        # Analyze false positives
        false_positives = [
            e for e in examples
            if not e.is_positive and e.improvement_impact is not None and e.improvement_impact < 0.5
        ]

        if false_positives:
            by_type_fp: Dict[str, List[TrainingExample]] = {}
            for fp in false_positives:
                by_type_fp.setdefault(fp.vulnerability_type, []).append(fp)

            for vuln_type, fps in by_type_fp.items():
                if len(fps) >= 3:
                    pattern = DiscoveredPattern(
                        id=f"pattern-fp-{len(self.discovered_patterns) + 1}",
                        name=f"False Positive Reduction: {vuln_type}",
                        description=(
                            f"Auto-discovered false positive filter for {vuln_type}. "
                            f"Sentinel flagged {len(fps)} safe code snippets. "
                            f"Adding confidence threshold adjustment."
                        ),
                        detection_pattern=f"safe_{vuln_type}_patterns",
                        severity="MEDIUM",
                        cwe_mapping=None,
                        discovery_source="false_positive_analysis",
                        confidence=0.6,
                    )
                    new_patterns.append(pattern)

        self.discovered_patterns.extend(new_patterns)
        self.stats.total_patterns_discovered += len(new_patterns)
        self.stats.active_patterns = len(self.discovered_patterns)

        if new_patterns:
            logger.info(f"Discovered {len(new_patterns)} new patterns from analysis failures")
            self._save_state()

        return new_patterns

    # ── Confidence Tuning ──

    def tune_confidence_thresholds(self, examples: List[TrainingExample]) -> Dict[str, Any]:
        """Automatically tune confidence thresholds based on evaluation results.

        Adjusts:
        - Minimum confidence for flagging vulnerabilities
        - Severity mapping based on detection accuracy
        - Agent routing confidence scores
        """
        if not examples:
            return {"adjustments": 0}

        # Calculate per-vulnerability-type accuracy
        by_type: Dict[str, List[float]] = defaultdict(list)
        for e in examples:
            if e.improvement_impact is not None:
                by_type[e.vulnerability_type].append(e.improvement_impact)

        adjustments = {}
        for vuln_type, impacts in by_type.items():
            avg_accuracy = sum(impacts) / len(impacts) if impacts else 0
            if avg_accuracy < 0.6:
                adjustments[vuln_type] = {
                    "accuracy": avg_accuracy,
                    "action": "add_detection_patterns",
                    "recommended_threshold_adjustment": 0.15,
                }
            elif avg_accuracy < 0.8:
                adjustments[vuln_type] = {
                    "accuracy": avg_accuracy,
                    "action": "fine_tune",
                    "recommended_threshold_adjustment": 0.05,
                }
            else:
                adjustments[vuln_type] = {
                    "accuracy": avg_accuracy,
                    "action": "no_change_needed",
                    "recommended_threshold_adjustment": 0.0,
                }

        self.stats.average_confidence_improvement = (
            sum(adjustments.get(t, {}).get("accuracy", 0) for t in adjustments) /
            len(adjustments) if adjustments else 0
        )

        self._save_state()
        return {
            "adjustments": adjustments,
            "total_types": len(adjustments),
            "types_needing_improvement": sum(
                1 for a in adjustments.values()
                if a["action"] != "no_change_needed"
            ),
        }

    # ── Full Improvement Cycle (v2.0) ──

    async def run_improvement_cycle(
        self,
        examples_count: int = 50,
        use_model_generation: bool = False,
        model_generation_ratio: float = 0.4,
        export_dataset: bool = True,
    ) -> Dict[str, Any]:
        """Run a complete self-improvement cycle with model-in-the-loop.

        v2.0: Now generates training data using real LLM inference,
        and can automatically export datasets for the fine-tuning pipeline.

        Steps:
        1. Generate training examples (templates + model-generated)
        2. Evaluate through orchestrator
        3. Discover patterns from mistakes
        4. Tune confidence thresholds
        5. Measure improvement
        6. Export dataset for fine-tuning (optional)
        7. Save state

        Args:
            examples_count: Number of examples to generate
            use_model_generation: Use real LLM for example generation
            model_generation_ratio: Fraction generated by LLM
            export_dataset: Export to JSONL for fine-tuning pipeline

        Returns:
            Improvement metrics
        """
        self.stats.total_improvement_cycles += 1
        start_time = time.time()
        cycle_id = f"cycle-{self.stats.total_improvement_cycles}"

        logger.info(f"=== Starting improvement cycle {cycle_id} "
                    f"(model_generation={use_model_generation}, "
                    f"ratio={model_generation_ratio}) ===")

        # Step 1: Generate examples (using model-in-the-loop if available)
        examples = await self.generate_training_batch(
            count=examples_count,
            use_model_generation=use_model_generation,
            model_generation_ratio=model_generation_ratio,
        )
        logger.info(f"Step 1: Generated {len(examples)} examples "
                    f"({sum(1 for e in examples if e.model_generated)} model-generated)")

        # Step 2: Evaluate
        evaluated = []
        batch_size = 10
        for i in range(0, len(examples), batch_size):
            batch = examples[i:i + batch_size]
            tasks = [self.evaluate_example(ex) for ex in batch]
            results = await asyncio.gather(*tasks)
            evaluated.extend(results)

        logger.info(f"Step 2: Evaluated {len(evaluated)} examples")

        # Step 3: Discover patterns
        patterns = self.discover_patterns_from_failures(evaluated)
        logger.info(f"Step 3: Discovered {len(patterns)} new patterns")

        # Step 4: Tune thresholds
        tuning = self.tune_confidence_thresholds(evaluated)
        logger.info(f"Step 4: Tuned thresholds for {tuning['total_types']} vulnerability types")

        # Step 5: Calculate metrics
        impacts = [e.improvement_impact for e in evaluated if e.improvement_impact is not None]
        avg_impact = sum(impacts) / len(impacts) if impacts else 0

        # Step 6: Export dataset for fine-tuning (NEW)
        exported_path = None
        if export_dataset:
            output_dir = os.path.join(self.storage_dir, "datasets")
            os.makedirs(output_dir, exist_ok=True)
            exported_path = self.export_train_val_split(
                output_dir=output_dir,
                max_examples=1000,
            )
            logger.info(f"Step 6: Exported fine-tuning dataset to {exported_path}")

        # Step 7: Record history
        cycle_record = {
            "cycle_id": cycle_id,
            "timestamp": datetime.utcnow().isoformat(),
            "duration_seconds": time.time() - start_time,
            "examples_generated": len(examples),
            "model_generated": sum(1 for e in examples if e.model_generated),
            "examples_evaluated": len(evaluated),
            "patterns_discovered": len(patterns),
            "average_accuracy": round(avg_impact, 3),
            "types_adjusted": tuning["types_needing_improvement"],
            "dataset_exported": exported_path is not None,
            "model_generation_enabled": use_model_generation,
        }
        self.improvement_history.append(cycle_record)

        self.stats.last_training_time = datetime.utcnow().isoformat()

        logger.info(
            f"=== Cycle {cycle_id} complete: "
            f"accuracy={avg_impact:.1%}, "
            f"patterns={len(patterns)}, "
            f"model_examples={cycle_record['model_generated']}, "
            f"dataset_exported={exported_path is not None}, "
            f"time={time.time() - start_time:.1f}s ==="
        )

        self._save_state()
        return cycle_record

    # ── Knowledge Distillation ──

    def extract_knowledge_base(self) -> Dict[str, Any]:
        """Extract all learned knowledge into a portable format.

        This knowledge base can be:
        - Loaded into new Sentinel instances
        - Shared between distributed nodes
        - Used to bootstrap new agents
        """
        return {
            "extracted_at": datetime.utcnow().isoformat(),
            "patterns": [
                {
                    "name": p.name,
                    "description": p.description,
                    "severity": p.severity,
                    "cwe": p.cwe_mapping,
                    "accuracy": p.accuracy,
                    "pattern": p.detection_pattern,
                }
                for p in self.discovered_patterns
            ],
            "confidence_adjustments": {
                "average": self.stats.average_confidence_improvement,
            },
            "vulnerability_types_covered": len(set(
                e.vulnerability_type for e in self.examples
            )),
            "training_examples_count": len(self.examples),
            "model_generated_examples": self.stats.model_generated_examples,
            "improvement_cycles": self.stats.total_improvement_cycles,
        }

    # ── Status ──

    def get_status(self) -> Dict[str, Any]:
        """Get self-play pipeline status."""
        vuln_types = set(e.vulnerability_type for e in self.examples)
        return {
            "total_examples": len(self.examples),
            "model_generated_examples": self.stats.model_generated_examples,
            "template_based_examples": len(self.examples) - self.stats.model_generated_examples,
            "total_patterns": len(self.discovered_patterns),
            "improvement_cycles": self.stats.total_improvement_cycles,
            "last_training": self.stats.last_training_time,
            "vulnerability_types_covered": len(vuln_types),
            "vulnerability_types": sorted(vuln_types),
            "average_accuracy": self.stats.average_confidence_improvement,
            "inference_engine_available": self._inference_engine is not None,
            "storage_dir": self.storage_dir,
            "recent_patterns": [
                {"name": p.name, "accuracy": p.accuracy, "source": p.discovery_source}
                for p in self.discovered_patterns[-5:]
            ],
            "recent_history": self.improvement_history[-5:],
        }

    def get_knowledge_summary(self) -> str:
        """Get a human-readable summary of all learned knowledge."""
        parts = []
        parts.append(f"Sentinel Self-Play Knowledge Base")
        parts.append(f"{'='*60}")
        parts.append(f"Training Examples: {self.stats.total_training_examples}")
        parts.append(f"  Template-generated: {self.stats.total_training_examples - self.stats.model_generated_examples}")
        parts.append(f"  Model-generated:   {self.stats.model_generated_examples}")
        parts.append(f"Discovered Patterns: {self.stats.total_patterns_discovered}")
        parts.append(f"Improvement Cycles: {self.stats.total_improvement_cycles}")
        parts.append(f"Active Patterns: {self.stats.active_patterns}")
        parts.append(f"Average Accuracy: {self.stats.average_confidence_improvement:.1%}")
        parts.append(f"Vuln Types Covered: {self.stats.total_vulnerability_types_covered}")
        parts.append(f"Inference Engine: {'Available' if self._inference_engine else 'Not available'}")
        parts.append("")
        parts.append("Discovered Patterns:")
        for p in self.discovered_patterns[-10:]:
            status = "ACTIVE" if p.accuracy > 0.7 else "LEARNING"
            parts.append(f"  [{status}] {p.name} (accuracy: {p.accuracy:.0%})")
        parts.append("")
        parts.append("Recent Improvements:")
        for h in self.improvement_history[-3:]:
            parts.append(f"  Cycle {h['cycle_id']}: accuracy={h['average_accuracy']:.0%}, "
                         f"patterns={h['patterns_discovered']}, "
                         f"model_examples={h.get('model_generated', 0)}")
        return "\n".join(parts)
