"""Report Generator Agent — Synthesizes multi-agent findings into professional reports.

This agent:
1. Collects findings from all agents
2. Correlates and prioritizes issues
3. Generates executive summaries, technical details, and remediation roadmaps
4. Supports multiple output formats (Markdown, JSON, PDF-ready)

Outputs reports suitable for:
- CISO/executive briefings
- Security team technical reports
- Compliance audit evidence
- Developer pull request comments
"""

import logging
from typing import Dict, List, Optional, Any
from datetime import datetime

from src.agents.base_agent import BaseAgent, AgentResult

logger = logging.getLogger(__name__)


class ReportGeneratorAgent(BaseAgent):
    """Specialized agent for generating comprehensive security reports."""

    REPORT_TEMPLATES = {
        "executive": """# Executive Security Report
**Generated by:** Sentinel Cyber AI
**Date:** {date}
**Status:** {status}

## Summary
{summary}

## Key Metrics
- **Total Findings:** {total_findings}
- **Critical:** {critical} | **High:** {high} | **Medium:** {medium} | **Low:** {low}
- **Confidence Score:** {confidence:.1%}
- **Agents Used:** {agents_used}

## Top Risks
{top_risks}

## Recommendations
{recommendations}

## Appendix
- Agents: {agent_details}
- Full findings: See technical report
""",
        "technical": """# Technical Security Report
**Generated by:** Sentinel Cyber AI
**Date:** {date}
**Analysis ID:** {task_id}

## Agent Analysis Details
{agent_results}

## Vulnerability Findings
{findings_detail}

## Remediation Plan
{remediation_plan}

## Methodology
Sentinel employs a multi-agent AI architecture:
1. **Code-Scanner** — Pattern-based + AI vulnerability detection
2. **Exploit-Analyzer** — Attack vector analysis and verification
3. **Patch-Generator** — Secure code fix generation
4. **Threat-Intelligence** — CVE/CWE correlation and threat feeds
5. **Report-Generator** — Result synthesis and reporting
""",
        "pull_request": """## 🔐 Sentinel Security Review — PR #{pr_number}

### Issues Found
{findings_list}

### Suggested Fixes
{suggested_fixes}

---
*Automated security review by Sentinel Cyber AI*
""",
        "slack": """🔐 *Sentinel Security Alert*

*Status:* {status}
*Confidence:* {confidence:.0%}
*Findings:* {finding_count}

{top_findings}

_View full report: {report_url}_""",
    }

    def __init__(self, model_name: str = "qwen3-235b"):
        super().__init__(
            name="Report-Generator",
            model_name=model_name,
            tools=["report_writer", "markdown_render", "pdf_generate"],
        )

    async def analyze(self, query: str, context: Optional[Dict[str, Any]] = None) -> AgentResult:
        """Generate a security report based on the query and agent results."""
        # This agent primarily synthesizes results from other agents
        # When called directly, it provides guidance on report generation
        return AgentResult(
            agent_name=self.name,
            status="success",
            summary="Report generator ready. Pass multi-agent results to generate reports.",
            confidence=1.0,
            details={
                "available_templates": list(self.REPORT_TEMPLATES.keys()),
                "formats": ["executive", "technical", "pull_request", "slack"],
            },
        )

    def generate_report(
        self,
        analysis_result: Dict[str, Any],
        report_type: str = "technical",
        **kwargs,
    ) -> str:
        """Generate a formatted report from multi-agent analysis results.

        Args:
            analysis_result: The output from orchestrator.process()
            report_type: One of "executive", "technical", "pull_request", "slack"
            **kwargs: Additional template variables

        Returns:
            Formatted report string
        """
        template = self.REPORT_TEMPLATES.get(report_type, self.REPORT_TEMPLATES["technical"])

        findings = analysis_result.get("findings", [])
        critical = sum(1 for f in findings if f.get("severity") == "CRITICAL")
        high = sum(1 for f in findings if f.get("severity") == "HIGH")
        medium = sum(1 for f in findings if f.get("severity") == "MEDIUM")
        low = sum(1 for f in findings if f.get("severity") == "LOW")

        # Build top risks (critical + high findings)
        top_risks_lines = []
        for f in findings:
            if f.get("severity") in ("CRITICAL", "HIGH"):
                top_risks_lines.append(
                    f"- **{f['severity']}**: {f.get('title', 'N/A')} — {f.get('description', '')[:150]}"
                )
        top_risks = "\n".join(top_risks_lines[:5]) or "No critical or high risks identified."

        # Build findings detail
        findings_detail_lines = []
        for i, f in enumerate(findings, 1):
            findings_detail_lines.append(
                f"### {i}. {f.get('title', 'Finding')} [{f.get('severity', 'INFO')}]\n"
                f"{f.get('description', '')}\n\n"
                f"*CWE: {f.get('cwe', 'N/A')} | Location: {f.get('location', 'N/A')}*\n"
            )
            if f.get("remediation"):
                findings_detail_lines.append(f"*Remediation:* {f['remediation']}\n")
        findings_detail = "\n".join(findings_detail_lines) or "No findings."

        # Build remediation plan
        remediation_lines = []
        for f in findings:
            if f.get("remediation"):
                remediation_lines.append(f"- {f.get('title', 'N/A')}: {f['remediation'][:200]}")
        remediation_plan = "\n".join(remediation_lines[:10]) or "No specific remediations identified."

        # Build agent details
        agent_results = analysis_result.get("agent_results", [])
        agent_lines = []
        for ar in agent_results:
            agent_lines.append(f"- **{ar.get('agent_name', 'N/A')}**: {ar.get('status', 'N/A')}")
        agent_details = "\n".join(agent_lines)

        # Build recommendations
        recommendations_lines = []
        if critical:
            recommendations_lines.append(f"🔴 **Immediate action required**: {critical} critical vulnerabilities.")
        if high:
            recommendations_lines.append(f"🟠 **High priority**: {high} high-severity issues need addressing.")
        recommendations_lines.append("✅ Run a full security audit after applying fixes.")
        recommendations = "\n".join(recommendations_lines[:3])

        # Build findings for PR/slack format
        findings_list = "\n".join(
            f"- [{f.get('severity', 'INFO')}] {f.get('title', 'N/A')}"
            for f in findings[:5]
        ) or "No issues found."

        suggested_fixes = "\n".join(
            f"- **{f.get('title', 'N/A')}**: {f.get('remediation', 'See technical report')[:150]}"
            for f in findings[:3]
        ) or "No fixes required."

        top_findings = "\n".join(
            f"• *{f.get('severity', 'INFO')}*: {f.get('title', 'N/A')}"
            for f in findings[:3]
        ) or "No issues detected."

        # Format the report
        return template.format(
            date=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
            status=analysis_result.get("status", "unknown").upper(),
            summary=analysis_result.get("summary", "No summary available"),
            total_findings=len(findings),
            critical=critical,
            high=high,
            medium=medium,
            low=low,
            confidence=analysis_result.get("confidence", 0),
            agents_used=", ".join(analysis_result.get("agents_used", [])),
            agent_results=agent_details,
            top_risks=top_risks,
            findings_detail=findings_detail,
            findings_list=findings_list,
            suggested_fixes=suggested_fixes,
            top_findings=top_findings,
            remediation_plan=remediation_plan,
            recommendations=recommendations,
            agent_details=agent_details,
            task_id=analysis_result.get("task_id", "N/A"),
            pr_number=kwargs.get("pr_number", "N/A"),
            report_url=kwargs.get("report_url", "#"),
            finding_count=len(findings),
        )

    def generate_executive_summary(self, analysis_result: Dict[str, Any]) -> str:
        """Generate a one-page executive summary."""
        findings = analysis_result.get("findings", [])
        critical = sum(1 for f in findings if f.get("severity") == "CRITICAL")
        high = sum(1 for f in findings if f.get("severity") == "HIGH")

        summary = (
            f"# Executive Security Summary\n\n"
            f"**Date:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}\n"
            f"**Analysis ID:** {analysis_result.get('task_id', 'N/A')}\n\n"
            f"## Overview\n"
            f"{analysis_result.get('summary', 'No summary')}\n\n"
            f"## Risk Profile\n"
            f"- **Critical:** {critical}\n"
            f"- **High:** {high}\n"
            f"- **Total:** {len(findings)}\n"
            f"- **Confidence:** {analysis_result.get('confidence', 0):.1%}\n\n"
        )

        if critical > 0 or high > 0:
            summary += (
                "## Critical Items\n"
                "The following items require immediate attention:\n\n"
            )
            for f in findings:
                if f.get("severity") in ("CRITICAL", "HIGH"):
                    summary += f"- **{f.get('title')}** — {f.get('description', '')[:200]}\n"

        return summary
